### ISSUE TITLE
Publish an update to match the documentation

### ISSUE THREAD

**Issue by azurstarshine** [mwclient/mwclient#330] opened 2024-04-25 02:07 UTC
I'm getting the following warning:

> WARNING:mwclient.client:Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/> for notice of API deprecations and breaking changes.
> WARNING:mwclient.client:Main-account login via "action=login" is deprecated and may stop working without warning. To continue login with "action=login", see [[Special:BotPasswords]]. To safely continue using main-account login, see "action=clientlogin".

That led me to the documentation that [`Site.login`](https://mwclient.readthedocs.io/en/latest/reference/site.html#mwclient.client.Site.login) is deprecated in favor of [`Site.clientlogin`](https://mwclient.readthedocs.io/en/latest/reference/site.html#mwclient.client.Site.clientlogin). All well and good, but `Site.clientlogin` *does not exist* in the most recently published version [from 2020](https://pypi.org/project/mwclient/#history).

This is confusing as a user of the library and makes the project look dead/abandoned. I suggest publishing an update to both the library and the documentation in the very near future (maybe within a month) to show that it is *not* dead and to avoid this sort of confusion. It's been 3 years since a release. That is very concerning if I want to depend on this library's continued stability, and I very much do. The official alternative, [pywikibot](https://doc.wikimedia.org/pywikibot/stable/), is a convoluted nightmare of object obsession and required on-disk configuration and wastes enormous amounts of time trying to figure out how it's supposed to work. This library is simple, clear cut, and has a much more Pythonic design. The release doesn't need to be 1.0. It can be 0.11. I'd just like to see *some* kind of release and consistency between the latest release and the docs.

**Comment by AdamWill** [comment] 2024-04-25 04:59
We are already planning a new release. Filing a long issue with a hectoring tone is not helping. This project is maintained by volunteers in our spare time, we all have day jobs and nobody is getting paid. When I'm not sitting here doing my day job at 10pm I'll try and get the release finished up. Thank you.

**Comment by AdamWill** [comment] 2024-05-04 18:40
This is effectively a dupe of #284 . as mentioned there I am working on a release workflow now.

**Closed by AdamWill** 2024-05-04 18:40 UTC
