### ISSUE TITLE
am I using oauth interface correctly?

### ISSUE THREAD

**Issue by cariaso** [mwclient/mwclient#152] opened 2017-05-03 17:21 UTC
example code at 
https://www.reddit.com/r/SNPedia/comments/68rhkr/cant_access_snpedia_with_oauth_tokens/dh2zo9p/

should make the question clear

**Comment by danmichaelo** [comment] 2017-05-05 23:14
You're using the interface correctly, and I cannot reproduce the problem using WMF servers. Answered on reddit, so closing this issue.

**Closed by danmichaelo** 2017-05-05 23:14 UTC
